# Generated by Django 5.2.7 on 2025-10-14 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official organization name', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('UNIVERSITY', 'University'), ('RESEARCH_INSTITUTE', 'Research Institute'), ('CORPORATION', 'Corporation'), ('GOVERNMENT', 'Government'), ('NON_PROFIT', 'Non-Profit'), ('CONSORTIUM', 'Consortium')], help_text='Organization category', max_length=50)),
                ('location', models.CharField(help_text='Geographic location', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Official website')),
                ('policies', models.JSONField(default=list, help_text='Research and usage policies')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='research_or_type_1a2017_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Position/role within organization', max_length=100)),
                ('start_date', models.DateField(help_text='Beginning of affiliation')),
                ('end_date', models.DateField(blank=True, help_text='End of affiliation (optional)', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary affiliation flag')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Given name', max_length=100)),
                ('last_name', models.CharField(help_text='Family name', max_length=100)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, unique=True)),
                ('orcid_id', models.CharField(blank=True, help_text='Persistent researcher ID (ORCID)', max_length=19, null=True, unique=True)),
                ('expertise_areas', models.JSONField(default=list, help_text='Research specializations')),
                ('research_interests', models.JSONField(default=list, help_text='Current focus areas')),
                ('organizations', models.ManyToManyField(related_name='researchers', through='research.OrganizationAffiliation', to='research.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organizationaffiliation',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researcher'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationaffiliation',
            unique_together={('researcher', 'organization', 'start_date')},
        ),
    ]
